name: LegendaryRunePlus
main: com.gyzer.LegendaryRunePlus
version: 1.0.1
api-version: 1.13
depend:
  - Vault
softdepend:
  - PlayerPoints
  - SX-Attribute
  - AttributePlus
commands:
  LegendaryRunePlus:
    aliases:
      - lrp
      - lr
      - runes
      - rune
      - lrune