name: LegendaryRunePlus
main: com.gyzer.LegendaryRunePlus
version: 2.0.1
depend:
  - Vault
softdepend:
  - PlayerPoints
  - SX-Attribute
  - AttributePlus
  - MythicLib
commands:
  LegendaryRunePlus:
    aliases:
      - lrp
      - lr
      - runes
      - rune
      - lrune